// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZrfAnSkZczwWhxldl_Ms1QLOkukTDWEI',
    appId: '1:870726322830:web:70d1dc3059f5f8f74cd7df',
    messagingSenderId: '870726322830',
    projectId: 'my-airdrop',
    authDomain: 'my-airdrop.firebaseapp.com',
    storageBucket: 'my-airdrop.appspot.com',
    measurementId: 'G-J0C6BMHZFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8qbc4wr9Cz8sjnWANKa2crwcjwj2gziA',
    appId: '1:870726322830:android:a6075dc5d06f62964cd7df',
    messagingSenderId: '870726322830',
    projectId: 'my-airdrop',
    storageBucket: 'my-airdrop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhKxZc7j7_b6T6Fh_qc_ldXkib-8gRZR0',
    appId: '1:870726322830:ios:08623d1f522a5da44cd7df',
    messagingSenderId: '870726322830',
    projectId: 'my-airdrop',
    storageBucket: 'my-airdrop.appspot.com',
    iosBundleId: 'com.example.myAirdrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhKxZc7j7_b6T6Fh_qc_ldXkib-8gRZR0',
    appId: '1:870726322830:ios:fb9eae4b27f138fc4cd7df',
    messagingSenderId: '870726322830',
    projectId: 'my-airdrop',
    storageBucket: 'my-airdrop.appspot.com',
    iosBundleId: 'com.example.myAirdrop.RunnerTests',
  );
}
